### ISSUE TITLE
Invalid wordlists: invalid names: [apiroutes-230528] error

### ISSUE THREAD

**Issue by CustosClarus** [assetnote/kiterunner#64]
My kr results are failing when I run the command

`└─$ kr scan http://10.10.234.107:8081/ -A=apiroutes-230528`

`5:05PM FTL failed to scan domain error="failed to apply option: failed to get wordlists: invalid names: [apiroutes-230528]"       `

I believe the name of apriroutes have changed as I read on www, everyone is using the 230528.

**Comment by siloed** [comment]
yes this list seem to get updated. you can view the latest by running:
`kr wordlist list`

it will list the latest list you have such as apiroutes-240128 for example.

had the same issue and was googling so hopefully this helps someone.
